CREATE SCHEMA IF NOT EXISTS cine;
SET SCHEMA cine;

-- =========================
-- TABLA USUARIOS
-- =========================
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(120) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'VIEWER')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- =========================
-- TABLA PELICULAS
-- =========================
CREATE TABLE IF NOT EXISTS peliculas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    titulo VARCHAR(200) NOT NULL,
    director VARCHAR(120),
    genero VARCHAR(60),
    anio_estreno INT CHECK (anio_estreno >= 1888),

    duracion_min INT CHECK (duracion_min IS NULL OR duracion_min > 0),
    pais_produccion VARCHAR(80),
    sinopsis VARCHAR(1000),

    -- 0..10 según especificación
    valoracion_media DECIMAL(3,1)
    CHECK (valoracion_media IS NULL OR (valoracion_media >= 0 AND valoracion_media <= 10)),

    imagen_portada VARCHAR(500),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- =========================
-- TABLA PUNTUACIONES
-- =========================
CREATE TABLE IF NOT EXISTS puntuaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    pelicula_id BIGINT NOT NULL,
    puntuacion INT NOT NULL CHECK (puntuacion BETWEEN 0 AND 10),
    rated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_puntuaciones_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES usuarios(id)
    ON DELETE CASCADE,

    CONSTRAINT fk_puntuaciones_pelicula
    FOREIGN KEY (pelicula_id)
    REFERENCES peliculas(id)
    ON DELETE CASCADE,

    CONSTRAINT uq_usuario_pelicula UNIQUE (usuario_id, pelicula_id)
    );

-- =========================
-- INDICES
-- =========================
CREATE INDEX IF NOT EXISTS idx_peliculas_genero ON peliculas(genero);
CREATE INDEX IF NOT EXISTS idx_peliculas_director ON peliculas(director);
CREATE INDEX IF NOT EXISTS idx_peliculas_anio ON peliculas(anio_estreno);
CREATE INDEX IF NOT EXISTS idx_peliculas_valoracion ON peliculas(valoracion_media);

CREATE INDEX IF NOT EXISTS idx_puntuaciones_usuario ON puntuaciones(usuario_id);
CREATE INDEX IF NOT EXISTS idx_puntuaciones_pelicula ON puntuaciones(pelicula_id);
