-- Usar schema cine (compatible con PostgreSQL y H2)
CREATE SCHEMA IF NOT EXISTS cine;
SET SCHEMA cine;

-- =========================
-- TABLA USUARIOS
-- =========================
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'VIEWER')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- =========================
-- TABLA PELICULAS
-- =========================
CREATE TABLE IF NOT EXISTS peliculas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    director VARCHAR(120),
    genero VARCHAR(60),
    anio_estreno INT CHECK (anio_estreno >= 1888),
    descripcion VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- =========================
-- TABLA PUNTUACIONES
-- =========================
CREATE TABLE IF NOT EXISTS puntuaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    pelicula_id BIGINT NOT NULL,
    puntuacion INT NOT NULL CHECK (puntuacion BETWEEN 1 AND 10),
    rated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_puntuaciones_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES usuarios(id)
    ON DELETE CASCADE,

    CONSTRAINT fk_puntuaciones_pelicula
    FOREIGN KEY (pelicula_id)
    REFERENCES peliculas(id)
    ON DELETE CASCADE,

    CONSTRAINT uq_usuario_pelicula UNIQUE (usuario_id, pelicula_id)
    );

-- =========================
-- INDICES
-- =========================
CREATE INDEX IF NOT EXISTS idx_peliculas_genero ON peliculas(genero);
CREATE INDEX IF NOT EXISTS idx_peliculas_director ON peliculas(director);
CREATE INDEX IF NOT EXISTS idx_puntuaciones_usuario ON puntuaciones(usuario_id);
CREATE INDEX IF NOT EXISTS idx_puntuaciones_pelicula ON puntuaciones(pelicula_id);
